/**
 * descriptors.ts — Aggregated IconDescriptor registry
 *
 * This file re-exports all generated icon descriptor arrays and provides
 * a unified lookup function by library key.
 *
 * The *-full.ts files are generated by:
 *   npm run generate-icons
 *   (runs: node scripts/generate-icons.mjs)
 *
 * Do NOT manually edit the *-full.ts files — regenerate them with the
 * script whenever a library package is upgraded.
 *
 * NOTE: This file will only compile after running `npm run generate-icons`
 * to create the three *-full.ts files.
 */

import type { IconDescriptor, LibraryKey } from '../types/icon';
import { lucideIconsFull } from './lucide-icons-full';
import { tablerIconsFull } from './tabler-icons-full';
import { phosphorIconsFull } from './phosphor-icons-full';

// ---------------------------------------------------------------------------
// Public exports
// ---------------------------------------------------------------------------

export { lucideIconsFull, tablerIconsFull, phosphorIconsFull };

/** All descriptors across every available library */
export const allDescriptors: IconDescriptor[] = [
  ...lucideIconsFull,
  ...tablerIconsFull,
  ...phosphorIconsFull,
];

/** Lookup descriptors by library key */
export function getDescriptorsByLibrary(key: LibraryKey): IconDescriptor[] {
  switch (key) {
    case 'lucide':   return lucideIconsFull;
    case 'tabler':   return tablerIconsFull;
    case 'phosphor': return phosphorIconsFull;
    default:         return [];
  }
}
